sudo: required

language: sh

before_install:
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version
    - sudo apt install p7zip-full
    - wget http://sec.cuc.edu.cn/huangwei/course/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z
    - 7z x -oexp0x04/shell web_log.tsv.7z

script:
  - bash exp0x04/images/pic.sh ./ -h
  - bash exp0x04/images/pic.sh ./ -c
  - bash exp0x04/images/pic.sh ./ -C
  - bash exp0x04/images/pic.sh ./ -w xxx
  - bash exp0x04/images/pic.sh ./ -p www
  - bash exp0x04/images/pic.sh ./ -s yyy
  - bash exp0x04/images/pic.sh ./ -t

  - bash exp0x04/shell/player.sh
  - bash exp0x04/shell/webanalyze.sh h
  - bash exp0x04/shell/webanalyze.sh 1
  - bash exp0x04/shell/webanalyze.sh 2
  - bash exp0x04/shell/webanalyze.sh 3
  - bash exp0x04/shell/webanalyze.sh 4
  - bash exp0x04/shell/webanalyze.sh 5
  - bash exp0x04/shell/webanalyze.sh /shuttle

after_script:
  - /usr/bin/shellcheck test.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
