sudo: required

language: sh

before_install:
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version
    - sudo apt install p7zip-full
    - wget http://sec.cuc.edu.cn/huangwei/course/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z
    - 7z x -oexp04 web_log.tsv.7z
    - cp exp0x04/shell/playser.sh play.sh
    - cp exp0x04/shell/webanalyze.sh webanalyze.sh
    - mkdir workspace
    - cp -a exp0x04/images/. workspace
    - cp exp0x04/shell/pic.sh workspace

script:
  - bash test.sh
  - bash /workspace/pic.sh -h
  - bash /workspace/pic.sh -c
  - bash /workspace/pic.sh -C
  - bash /workspace/pic.sh -w xxx
  - bash /workspace/pic.sh -p www
  - bash /workspace/pic.sh -s yyy
  - bash /workspace/pic.sh -t

  - bash player.sh
  - bash webanalyze.sh h
  - bash webanalyze.sh 1
  - bash webanalyze.sh 2
  - bash webanalyze.sh 3
  - bash webanalyze.sh 4
  - bash webanalyze.sh 5
  - bash webanalyze.sh /shuttle

after_script:
  - /usr/bin/shellcheck test.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
